-- Define the steps for the grind path
steps = {
    -- Floor 0: nw s s (n e e) n (s s) d
    {"kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "e", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 1: w w s e (w s) e e u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 2: s s e e d
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 3: n n se e nw e d
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 4: w (e e) (w n) ne w w u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 6 (first occurrence): n n sw nw s s u
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 5 (first occurrence): n e e s (n nw) d
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 8: se (nw ne) w w s s u
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 5 (second occurrence): (n ne u)
    {"g", "n", "ne", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 7: e e (w s) s d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 11: s (n n) se se n n (s d)
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 10: e e (w s) sw e e d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 9: e e sw s d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 6 (second occurrence): (n n sw w s d)
    {"g", "n", "n", "sw", "w", "s", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 12: w w s s e e n w u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 13: w w (e s) s d
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 14: s (n e) e s (n sw) sw e e u
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 16: w w n n e s (n e) u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 15: n e se (nw w n) e e d
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "w", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 18: w w s s e e d
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 17: se s (n w) w s d
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 19: s (n n) (s e) e s (n n) se e e se se proceed
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "proceed", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 20: se s nw w s d
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 21: n n se se n n u
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 24: s s nw sw n n d
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 25: e e sw w s e e d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 26: s w (e e) n n w w s u
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 27: s s e e n n u
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 28: e e sw s u
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 29: w w s e e s w w u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 24 (second occurrence): (s s nw nw u)
    {"g", "s", "s", "nw", "nw", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 23: s (n e) e s (n sw) sw e e d
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 20 (second occurrence): (sw s d)
    {"g", "sw", "s", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 21 (second occurrence): (n e se n n d)
    {"g", "n", "e", "se", "n", "n", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 30: e e (w s) s e (w w) d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 31: e ne w w n e d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 32: w n e e (w sw s) e e d
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "sw", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 33: n ne w w d
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 34: s s (n w) nw s s d
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 20 (third occurrence): (sw s u)
    {"g", "sw", "s", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 22: e e sw s d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 35: e (w w) ne w n e e d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 37: s (n ne) se w se u
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 36: w w s s e e n w u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 38: n n se ne s s d
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 39: e (w w) s e sw e e e e proceed
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "proceed", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 40: ne w w (e s s) e (w w) u
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "s", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 42: w w s e sw e e u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 41: s se n e n u
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 44: w w s e (w s) e e d
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 45: e e (w w n) e nw e e d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "w", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},
    {"kill balangool"},

    -- Floor 46: s (n n) se se n n u
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 50: e se (nw sw) s e u
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 48: w w s e (w s) e e d
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 47: n n (s w) nw s s <enter portal>
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "enter portal", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 49: w w n n u
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "u", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 41 (second occurrence): (s se ne n d)
    {"g", "s", "se", "ne", "n", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 43: e (w w) n e ne w w d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 51: se n n (s w w) s (n n) d
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "w", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 52: w n n se se n n w d
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 53: w w s e e s w w d
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 55: nw e nw sw s d
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 54: sw s (n n) w <enter portal>
    {"g", "sw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "enter portal", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 56: e n w (s w) n n e e d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 57: e e (w w se) w s e e d
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "w", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 58: se w w (e n ne) w w s d
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "n", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "w", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "s", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "d", "tactical", "kill balangool"},
    {"kill balangool"},

    -- Floor 59: n nw (se ne) e e e se se e e ne e
    {"g", "n", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "nw", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "se", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "ne", "tactical", "kill balangool"},
    {"kill balangool"},
    {"g", "e", "tactical", "kill balangool"},
    {"get figurine", "get barrier", "d"},
    {"door", "exit", "tactical", "kill balangool"}
}

-- Global variables
currentStepIndex = 0
seczGrindActive = false
pauseGrind = false

-- Function to process the next step
function processNextStep()
    if not seczGrindActive then
        ColourNote("red", "black", "Grind stopped.")
        return
    end

    -- Check if all steps are completed
    if currentStepIndex >= #steps then
        ColourNote("green", "black", "Section Z exp grind path completed!")
        seczGrindActive = false
        return
    end

    -- Move to the next step
    currentStepIndex = currentStepIndex + 1
    local commands = steps[currentStepIndex]

    -- Send all commands for this step
    for _, command in ipairs(commands) do
        Send(command)
    end
end

-- Trigger: Recovery Finished (advances to next step)
function onRecovery(name, line, wildcards)
    if seczGrindActive and not pauseGrind then
        processNextStep()
    end
end

-- Function to start the grind
function startGrind()
    if seczGrindActive then
        ColourNote("yellow", "black", "Grind already in progress!")
        return
    end

    seczGrindActive = true
    currentStepIndex = 0
    ColourNote("cyan", "black", "Starting Section Z exp grind...")
    processNextStep()
end

-- Function to stop the grind
function stopGrind()
    seczGrindActive = false
    ColourNote("red", "black", "Section Z exp grind stopped.")
end

-- Function to pause the grind
function pauseGrindFunction()
    pauseGrind = true
    ColourNote("yellow", "black", "Grind paused.")
end

-- Function to resume the grind
function resumeGrindFunction()
    if seczGrindActive and pauseGrind then
        pauseGrind = false
        ColourNote("cyan", "black", "Resuming grind...")
        processNextStep()
    end
end
